### PR TITLE
fix: update example theme file

### LINKED ISSUE #157: [BUG] Decoding using flutter_theme throws cast error
**Platform**

MacOS / Flutter 2.5.3

**Steps To Reproduce**

1. Clone the example flutter project and start it in debug mode
2. Enable catching uncaught exceptions in VS Code

**Expected Behavior**

The theme should be decoded without throwing an exception.

**Actual behaviour**
The application waits when decoding the theme and throws an Cast Error exception:
"Null check operator used on a null value"

**Screenshots**
image

image

**Additional Context**

### PR DESCRIPTION
**Pull request by zeshuaro**
- Regenerate example theme file with Flutter SDK 2.5.3
- Fix #157

### CODE REVIEW

**Comment by pauli2406** [comment]
Thanks for the fast fix!
Though I wonder what was exactly the issue, just the number format?
Because I face the similar in my own project when exporting an advanced theme from your hosted version.
Do you have any recommendation for this?
As a workaround I currently disabled the theme validation for now:
`
 return ThemeDecoder.decodeThemeData(
    themeJson,
    validate: false,
  )!;
`
I attached my file as a pastebin.
https://pastebin.com/nn7sv4cg

**Comment by zeshuaro** [comment]
@pauli2406 There was a [breaking change](https://docs.flutter.dev/release/breaking-changes/theme-data-accent-properties) in the `ThemeData` class in Flutter 2.5. I use the package [json_theme](https://pub.dev/packages/json_theme) to encode and decode, which has also been updated to validate the latest schema/properties in `ThemeData`. 

On the other hand, the JSON theme file generated in the example app was created using an older version of Flutter. And so the issue was that the file doesn't match the latest schema/properties anymore and failed the validations.

In your case where the generated theme doesn't work on your project. My guess is you're using an older version of `json_theme` in your project. Note that Flutter Theme is running on Flutter 2.5.3 with `json_theme: ^3.0.0`. If your project isn't using these versions, there may be compatibility issues. You'll either have to update Flutter on your machine and the package `json_theme`, or you can find an older version of Flutter Theme [here](https://github.com/zeshuaro/flutter_theme/releases) and run it locally.

**Comment by pauli2406** [comment]
@zeshuaro Thank you for the additional information.

I am currently running Flutter 2.5.3 and json_theme ^3.1.2+1. So that should be fine. 
Though to test it out I downgraded to ^3.0.0 but the error still applies.

So my next step was to check if the theme json your tool creates may requires a recreation so I manually recreated it and exported a new json.
Actually the format changed a lot when comparing both in a diff window.

Unfortunately this still did not help. I can recreate this issue when using the example project and use the latest exported json advanced theme in there. To try it out you can find the latest theme.json in the following paste bin:
[Theme.json](https://pastebin.com/g9t5VCNi)

Do you have any idea which property may be the culprit over there? Can you verify that advanced themes work for you with validation enabled?

Cheers,
Marcel

**Comment by zeshuaro** [comment]
@pauli2406 Thanks for testing things out on your end. The issue is actually reproducible on both basic and advanced themes. I couldn't figure out the cause of it but I think it's coming from the package when it was doing the schema validations.

I will check with the package repo and see if they can address it on their end. I've also reopened your issue and will follow-up from there.

Note that even though the exception was thrown, I think the theme data is still being decoded properly.

**Comment by pauli2406** [comment]
Yes, i can confirm that the theme is correctly decoded and used within my application. Though I have not assigned every property so it could be that some edge cases and less important properties do not work correctly. The exception that is thrown is unfortunately not really verbose and provides no hint about which key within the json is problematic.
Maybe they can improve this within json_theme to improve debugging.

For now it may also makes sense to add the workaround with disabling the validation for now to your user guide on how to use the generated theme within a application.

**Comment by zeshuaro** [comment]
I don't think it's an edge case as I can even reproduce the same issue using the example json themes they provided. I've created an issue on their side and hopefully they'll address it.

**Pull request merged**
